import {
  SiReact,
  SiVuedotjs,
  SiNextdotjs,
  SiNodedotjs,
  SiExpress,
  SiMongodb,
  SiMongoose,
  SiJsonwebtokens,
  SiTailwindcss,
  SiVite,
  SiFigma,
  SiPython,
  SiDjango,
  SiSpringboot,
  SiMysql,
  SiSqlite,
  SiFirebase,
  SiCloudinary,
  SiGit,
  SiJest,
  SiSonarqubeserver,
  SiCamunda,
  SiMocha,
  SiReactrouter,
  SiScikitlearn,
  SiPostgresql,
  SiWordpress,
} from 'react-icons/si'
import { FaJava } from 'react-icons/fa6'

// Maps a plain-text tech/skill name (as used in data/*.js) to its brand icon component.
// Anything not listed here just renders as text — no icon required for every entry.
export const TECH_ICONS = {
  'React': SiReact,
  'React.js': SiReact,
  'React 18': SiReact,
  'React 19': SiReact,
  'React Router': SiReactrouter,
  'Vue.js': SiVuedotjs,
  'Next.js': SiNextdotjs,
  'Node.js': SiNodedotjs,
  'Express': SiExpress,
  'Express 5': SiExpress,
  'MongoDB': SiMongodb,
  'Mongoose': SiMongoose,
  'JWT': SiJsonwebtokens,
  'JWT Auth': SiJsonwebtokens,
  'Tailwind CSS': SiTailwindcss,
  'Vite': SiVite,
  'Figma': SiFigma,
  'Python': SiPython,
  'Django': SiDjango,
  'Spring Boot 3': SiSpringboot,
  'Spring Boot': SiSpringboot,
  'MySQL': SiMysql,
  'SQLite': SiSqlite,
  'Firebase Auth': SiFirebase,
  'Firestore': SiFirebase,
  'Cloudinary': SiCloudinary,
  'Git': SiGit,
  'Git / GitHub': SiGit,
  'Jest': SiJest,
  'SonarQube': SiSonarqubeserver,
  'Camunda (BPMN workflows)': SiCamunda,
  'Mocha/Chai': SiMocha,
  'Java': FaJava,
  'scikit-learn': SiScikitlearn,
  'PostgreSQL': SiPostgresql,
  'WordPress': SiWordpress,
}
